### ISSUE TITLE
Java/Android SDK Timeout When stopping Inventory Stream

### ISSUE THREAD

**Issue by challgren** [NordicID/nur_sdk#13]
So when trying to stop an inventory that is running the following exception is thrown `java.lang.NullPointerException: Attempt to invoke virtual method 'int com.nordicid.nurapi.UartService.getConnState()' on a null object reference` the line that is crashing is `App.mApi!!.stopInventoryStream()`

Since this seems to be in the UartService I really have no way to debug or come up with a solution. Can your please provide some advice or suggestions?

```
05-22 09:46:29.024 D/NurApiSmartPairAutoConnect(27030): setAddress Unknown
05-22 09:46:29.024 D/NurApiSmartPairAutoConnect(27030): start()
05-22 09:46:29.025 D/NurApiSmartPairAutoConnect(27030): startConnecting NULL
05-22 09:46:29.025 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:29.029 D/BleScanner(27030): locationMode = 2
05-22 09:46:29.032 I/BleScanner(27030): onScanStarted() mScanning false
05-22 09:46:29.041 D/BluetoothAdapter(27030): isLeEnabled(): ON
05-22 09:46:29.044 D/BluetoothLeScanner(27030): onScannerRegistered() - status=0 scannerId=11 mScannerId=0
05-22 09:46:29.098 D/OpenGLRenderer(27030): HWUI GL Pipeline
05-22 09:46:29.177 I/Adreno  (27030): QUALCOMM build                   : 368094a, I26dffed9a4
05-22 09:46:29.177 I/Adreno  (27030): Build Date                       : 12/03/17
05-22 09:46:29.177 I/Adreno  (27030): OpenGL ES Shader Compiler Version: EV031.22.00.01
05-22 09:46:29.177 I/Adreno  (27030): Local Branch                     : 
05-22 09:46:29.177 I/Adreno  (27030): Remote Branch                    : quic/gfx-adreno.lnx.1.9.r3-rel
05-22 09:46:29.177 I/Adreno  (27030): Remote Branch                    : NONE
05-22 09:46:29.177 I/Adreno  (27030): Reconstruct Branch               : NOTHING
05-22 09:46:29.187 I/Adreno  (27030): PFP: 0x005ff087, ME: 0x005ff063
05-22 09:46:29.193 I/OpenGLRenderer(27030): Initialized EGL, version 1.4
05-22 09:46:29.194 D/OpenGLRenderer(27030): Swap behavior 2
05-22 09:46:29.197 D/NurApiSmartPairAutoConnect(27030): Added device 00:21:AD:13:12:6B
05-22 09:46:29.621 E/PUSHLINK(27030): Exception sent.
05-22 09:46:29.781 I/zygote  (27030): Do partial code cache collection, code=31KB, data=25KB
05-22 09:46:29.782 I/zygote  (27030): After code cache collection, code=30KB, data=25KB
05-22 09:46:29.782 I/zygote  (27030): Increasing code cache capacity to 128KB
05-22 09:46:29.796 E/PUSHLINK(27030): Device successfully registered!
05-22 09:46:30.148 D/NurApiSmartPairAutoConnect(27030): startConnecting 00:21:AD:13:12:6B
05-22 09:46:30.171 D/NurApiBLEAutoConnect(27030): onServiceConnected NEW service
05-22 09:46:30.171 D/UartService(27030): connect addr 00:21:AD:13:12:6B; mContext com.truepedigree.newportreader.ui.activities.MainActivity@7e6c08e
05-22 09:46:30.173 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:30.174 D/BleScanner(27030): locationMode = 2
05-22 09:46:30.174 I/BleScanner(27030): onScanStarted() mScanning true
05-22 09:46:30.174 D/UartService(27030): started device scan
05-22 09:46:30.264 D/UartService(27030): onDeviceFound() ADDR MATCH; mConnectionState 0
05-22 09:46:30.264 D/UartService(27030): connectInternal() 00:21:AD:13:12:6B
05-22 09:46:30.265 W/NurApiBLEAutoConnect(27030): onConnStateChanged 1; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:30.265 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 1
05-22 09:46:30.391 W/UartService(27030): connect 00:21:AD:13:12:6B
05-22 09:46:30.391 I/UartService(27030): Trying to create a new connection
05-22 09:46:30.393 D/BluetoothGatt(27030): connect() - device: 00:21:AD:13:12:6B, auto: false
05-22 09:46:30.393 D/BluetoothGatt(27030): registerApp()
05-22 09:46:30.393 D/BluetoothGatt(27030): registerApp() - UUID=0fcdfe2d-8477-471d-910f-285ad1373836
05-22 09:46:30.394 I/UartService(27030): Connection created
05-22 09:46:30.395 D/BluetoothGatt(27030): onClientRegistered() - status=0 clientIf=12
05-22 09:46:30.855 D/BluetoothGatt(27030): onClientConnectionState() - status=0 clientIf=12 device=00:21:AD:13:12:6B
05-22 09:46:30.857 I/UartService(27030): onConnectionStateChange -> "CONNECTED"
05-22 09:46:30.857 I/UartService(27030): Attempting to start service discovery
05-22 09:46:31.021 I/zygote  (27030): Do partial code cache collection, code=61KB, data=59KB
05-22 09:46:31.022 I/zygote  (27030): After code cache collection, code=61KB, data=59KB
05-22 09:46:31.022 I/zygote  (27030): Increasing code cache capacity to 256KB
05-22 09:46:31.025 I/zygote  (27030): Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
05-22 09:46:31.098 I/zygote  (27030): Do full code cache collection, code=108KB, data=88KB
05-22 09:46:31.100 I/zygote  (27030): After code cache collection, code=83KB, data=56KB
05-22 09:46:31.342 D/BluetoothGatt(27030): onConnectionUpdated() - Device=00:21:AD:13:12:6B interval=6 latency=0 timeout=500 status=0
05-22 09:46:31.371 I/Choreographer(27030): Skipped 31 frames!  The application may be doing too much work on its main thread.
05-22 09:46:31.472 W/UartService(27030): start discoverServices
05-22 09:46:31.473 D/BluetoothGatt(27030): discoverServices() - device: 00:21:AD:13:12:6B
05-22 09:46:32.768 D/BluetoothGatt(27030): onClientConnectionState() - status=40 clientIf=12 device=00:21:AD:13:12:6B
05-22 09:46:32.768 I/UartService(27030): onConnectionStateChange -> "DISCONNECTED"
05-22 09:46:32.769 W/NurApiBLEAutoConnect(27030): onConnStateChanged 0; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:32.769 W/NurApiBLEAutoConnect(27030): disconnect
05-22 09:46:32.769 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 0
05-22 09:46:32.769 D/UartService(27030): connect addr 00:21:AD:13:12:6B; mContext com.truepedigree.newportreader.ui.activities.MainActivity@7e6c08e
05-22 09:46:32.771 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:32.773 D/BleScanner(27030): locationMode = 2
05-22 09:46:32.773 I/BleScanner(27030): onScanStarted() mScanning true
05-22 09:46:32.773 D/UartService(27030): started device scan
05-22 09:46:32.773 I/UartService(27030): Disconnected from GATT server.
05-22 09:46:32.781 I/zygote  (27030): Do partial code cache collection, code=121KB, data=102KB
05-22 09:46:32.782 I/zygote  (27030): After code cache collection, code=121KB, data=102KB
05-22 09:46:32.782 I/zygote  (27030): Increasing code cache capacity to 512KB
05-22 09:46:32.954 D/UartService(27030): onDeviceFound() ADDR MATCH; mConnectionState 0
05-22 09:46:32.954 D/UartService(27030): connectInternal() 00:21:AD:13:12:6B
05-22 09:46:32.954 W/NurApiBLEAutoConnect(27030): onConnStateChanged 1; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:32.954 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 1
05-22 09:46:33.055 W/UartService(27030): connect 00:21:AD:13:12:6B
05-22 09:46:33.055 D/BluetoothGatt(27030): cancelOpen() - device: 00:21:AD:13:12:6B
05-22 09:46:33.056 D/BluetoothGatt(27030): close()
05-22 09:46:33.056 D/BluetoothGatt(27030): unregisterApp() - mClientIf=12
05-22 09:46:33.057 I/UartService(27030): Trying to create a new connection
05-22 09:46:33.058 D/BluetoothGatt(27030): connect() - device: 00:21:AD:13:12:6B, auto: false
05-22 09:46:33.058 D/BluetoothGatt(27030): registerApp()
05-22 09:46:33.059 D/BluetoothGatt(27030): registerApp() - UUID=55236f3e-2c84-44bc-b328-833f5c031f7e
05-22 09:46:33.060 I/UartService(27030): Connection created
05-22 09:46:33.060 D/BluetoothGatt(27030): onClientRegistered() - status=0 clientIf=12
05-22 09:46:33.495 D/BluetoothGatt(27030): onClientConnectionState() - status=133 clientIf=12 device=00:21:AD:13:12:6B
05-22 09:46:33.495 I/UartService(27030): onConnectionStateChange -> "DISCONNECTED"
05-22 09:46:33.495 W/NurApiBLEAutoConnect(27030): onConnStateChanged 0; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:33.495 W/NurApiBLEAutoConnect(27030): disconnect
05-22 09:46:33.496 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 0
05-22 09:46:33.496 D/UartService(27030): connect addr 00:21:AD:13:12:6B; mContext com.truepedigree.newportreader.ui.activities.MainActivity@7e6c08e
05-22 09:46:33.497 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:33.499 D/BleScanner(27030): locationMode = 2
05-22 09:46:33.499 I/BleScanner(27030): onScanStarted() mScanning true
05-22 09:46:33.499 D/UartService(27030): started device scan
05-22 09:46:33.499 I/UartService(27030): Disconnected from GATT server.
05-22 09:46:33.828 D/UartService(27030): onDeviceFound() ADDR MATCH; mConnectionState 0
05-22 09:46:33.828 D/UartService(27030): connectInternal() 00:21:AD:13:12:6B
05-22 09:46:33.828 W/NurApiBLEAutoConnect(27030): onConnStateChanged 1; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:33.829 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 1
05-22 09:46:33.929 W/UartService(27030): connect 00:21:AD:13:12:6B
05-22 09:46:33.929 D/BluetoothGatt(27030): cancelOpen() - device: 00:21:AD:13:12:6B
05-22 09:46:33.933 D/BluetoothGatt(27030): close()
05-22 09:46:33.933 D/BluetoothGatt(27030): unregisterApp() - mClientIf=12
05-22 09:46:33.935 I/UartService(27030): Trying to create a new connection
05-22 09:46:33.937 D/BluetoothGatt(27030): connect() - device: 00:21:AD:13:12:6B, auto: false
05-22 09:46:33.937 D/BluetoothGatt(27030): registerApp()
05-22 09:46:33.938 D/BluetoothGatt(27030): registerApp() - UUID=f9c0bd2e-7234-428b-9338-9d3e05fdde08
05-22 09:46:33.941 I/UartService(27030): Connection created
05-22 09:46:33.943 D/BluetoothGatt(27030): onClientRegistered() - status=0 clientIf=12
05-22 09:46:34.562 D/BluetoothGatt(27030): onClientConnectionState() - status=0 clientIf=12 device=00:21:AD:13:12:6B
05-22 09:46:34.562 I/UartService(27030): onConnectionStateChange -> "CONNECTED"
05-22 09:46:34.562 I/UartService(27030): Attempting to start service discovery
05-22 09:46:34.663 W/UartService(27030): start discoverServices
05-22 09:46:34.664 D/BluetoothGatt(27030): discoverServices() - device: 00:21:AD:13:12:6B
05-22 09:46:35.049 D/BluetoothGatt(27030): onConnectionUpdated() - Device=00:21:AD:13:12:6B interval=6 latency=0 timeout=500 status=0
05-22 09:46:35.857 W/UartService(27030): discoverServices jammed, restart
05-22 09:46:35.858 D/BluetoothGatt(27030): discoverServices() - device: 00:21:AD:13:12:6B
05-22 09:46:35.975 D/BluetoothGatt(27030): onSearchComplete() = Device=00:21:AD:13:12:6B Status=0
05-22 09:46:35.977 W/UartService(27030): onServicesDiscovered; status 0
05-22 09:46:35.978 D/BluetoothGatt(27030): setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
05-22 09:46:35.983 I/UartService(27030): CONNECTED
05-22 09:46:35.983 W/NurApiBLEAutoConnect(27030): onConnStateChanged 2; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:35.984 W/NurApiBLEAutoConnect(27030): onConnStateChanged done 2
05-22 09:46:36.046 D/BluetoothGatt(27030): onConnectionUpdated() - Device=00:21:AD:13:12:6B interval=39 latency=0 timeout=500 status=0
05-22 09:46:36.984 D/NurApiBLEAutoConnect(27030): ConnectApiRunnable; mService com.nordicid.nurapi.UartService@3afb110
05-22 09:46:36.988 W/NurApiBLEAutoConnect(27030): connect
05-22 09:46:36.989 I/NurApiBLETransport(27030): connect OK
05-22 09:46:38.672 D/NurApiSmartPairAutoConnect(27030): Connected
05-22 09:46:38.985 D/BluetoothGatt(27030): readRssi() - device: 00:21:AD:13:12:6B
05-22 09:46:46.128 I/zygote  (27030): Thread[3,tid=27036,WaitingInMainSignalCatcherLoop,Thread*=0xae984c00,peer=0x138000e8,"Signal Catcher"]: reacting to signal 3
05-22 09:46:46.128 I/zygote  (27030): 
05-22 09:46:46.322 I/zygote  (27030): Wrote stack traces to '/data/anr/traces.txt'
05-22 09:46:50.947 D/BluetoothGatt(27030): onClientConnectionState() - status=40 clientIf=12 device=00:21:AD:13:12:6B
05-22 09:46:50.947 I/UartService(27030): onConnectionStateChange -> "DISCONNECTED"
05-22 09:46:50.949 W/NurApiBLEAutoConnect(27030): onConnStateChanged 0; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:50.949 W/NurApiBLEAutoConnect(27030): disconnect
05-22 09:46:55.901 I/NurApiBLETransport(27030): disconnect OK
05-22 09:46:55.904 W/System.err(27030): java.lang.Exception: NurApi.connect() : connection failed. connFailedAt 0
05-22 09:46:55.905 W/System.err(27030): 	at com.nordicid.nurapi.NurApi.connect(NurApi.java:1900)
05-22 09:46:55.905 W/System.err(27030): 	at com.nordicid.nurapi.NurApiBLEAutoConnect$3$1.run(NurApiBLEAutoConnect.java:180)
05-22 09:46:55.905 W/NurApiBLEAutoConnect(27030): reconnect on failure
05-22 09:46:55.906 D/UartService(27030): connect addr 00:21:AD:13:12:6B; mContext com.truepedigree.newportreader.ui.activities.MainActivity@7e6c08e
05-22 09:46:55.909 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:55.915 D/BleScanner(27030): locationMode = 2
05-22 09:46:55.915 I/BleScanner(27030): onScanStarted() mScanning true
05-22 09:46:55.915 D/UartService(27030): started device scan
05-22 09:46:56.684 D/NurApiSmartPairAutoConnect(27030): Disconnected! Restarting connection
05-22 09:46:56.684 D/NurApiBLEAutoConnect(27030): onStop
05-22 09:46:56.687 D/NurApiBLEAutoConnect(27030): onStopInternal() disconnect; com.nordicid.nurapi.UartService@3afb110
05-22 09:46:56.687 D/NurApiBLEAutoConnect(27030): onStopInternal() close service
05-22 09:46:56.691 W/UartService(27030): close()
05-22 09:46:56.694 W/UartService(27030): close() mBluetoothGatt close
05-22 09:46:56.694 D/BluetoothGatt(27030): cancelOpen() - device: 00:21:AD:13:12:6B
05-22 09:46:56.695 D/BluetoothGatt(27030): close()
05-22 09:46:56.696 D/BluetoothGatt(27030): unregisterApp() - mClientIf=12
05-22 09:46:56.697 W/UartService(27030): close() mBluetoothGatt closed
05-22 09:46:56.697 D/NurApiSmartPairAutoConnect(27030): startConnecting NULL
05-22 09:46:56.698 I/BleScanner(27030): scanDevices() mOwner com.truepedigree.newportreader.App@227a05c
05-22 09:46:56.701 D/BleScanner(27030): locationMode = 2
05-22 09:46:56.701 I/BleScanner(27030): onScanStarted() mScanning true
05-22 09:47:05.906 W/BluetoothGatt(27030): Unhandled exception in callback
05-22 09:47:05.906 W/BluetoothGatt(27030): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.nordicid.nurapi.UartService.getConnState()' on a null object reference
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at com.nordicid.nurapi.NurApiBLEAutoConnect.onConnStateChanged(NurApiBLEAutoConnect.java:229)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at com.nordicid.nurapi.UartService.setConnState(UartService.java:80)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at com.nordicid.nurapi.UartService$1.onConnectionStateChange(UartService.java:151)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:244)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:711)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.bluetooth.BluetoothGatt.-wrap0(Unknown Source:0)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:240)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
05-22 09:47:05.906 W/BluetoothGatt(27030): 	at android.os.Binder.execTransact(Binder.java:674)
05-22 09:47:20.905 D/AndroidRuntime(27030): Shutting down VM
05-22 09:47:20.908 E/AndroidRuntime(27030): FATAL EXCEPTION: main
05-22 09:47:20.908 E/AndroidRuntime(27030): Process: com.truepedigree.newportreader, PID: 27030
05-22 09:47:20.908 E/AndroidRuntime(27030): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
05-22 09:47:20.908 E/AndroidRuntime(27030): Caused by: java.lang.reflect.InvocationTargetException
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at java.lang.reflect.Method.invoke(Native Method)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	... 1 more
05-22 09:47:20.908 E/AndroidRuntime(27030): Caused by: java.util.concurrent.TimeoutException
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.nordicid.nurapi.NurApi.exchangeCommand(NurApi.java:3117)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.nordicid.nurapi.NurApi.exchangeCommand(NurApi.java:3133)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.nordicid.nurapi.NurApi.stopInventoryStream(NurApi.java:7637)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.truepedigree.newportreader.ui.activities.BatchActivity.stopInventory(BatchActivity.kt:134)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at com.truepedigree.newportreader.ui.activities.BatchActivity$IOChangeEvent$1.run(BatchActivity.kt:422)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at android.os.Handler.handleCallback(Handler.java:789)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at android.os.Looper.loop(Looper.java:164)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	at android.app.ActivityThread.main(ActivityThread.java:6694)
05-22 09:47:20.908 E/AndroidRuntime(27030): 	... 3 more
```

**Comment by AriPoy** [comment]
It looks like transport has been disconnected and that's reason why stopInventory and other NurApi commands throws exception because no transport to device.
You need to surround stopInventory and other NurApi commands with Try..Catch in order to handle exceptions properly. otherwise FATAL happens and app crash.

**Comment by challgren** [comment]
Ok understandable, but why is it throwing a NullPointerException instead of a NurApiException? I specifically catch NurApiException as I know the reason for the crash is more than likely a Timeout of some nature but a NullPointerException is a bit different. I'm just trying to find out how to reproduce/prevent this NullPointerException
