### ISSUE TITLE
NurApiConnectTransport error 4098

### ISSUE THREAD

**Issue by SteGriff** [NordicID/nur_sdk#2]
Hi again,

I am building a minimal UWP app which will run on an x64 PC to connect to an EXA51. I have based my app on the latest Win10_UWPSample, using version 1.9.6 of the library. I am also including the same copy of `NURAPI.dll` as used by the [UWP sample app][uwp], and I *am* copying it to the output directory.

The `NurDeviceWatcher` works fine and successfully discovers my paired device.

I am building the app for Debug x86 because the sample app works fine in this configuration.

[uwp]: https://github.com/NordicID/nur_sample_windows/tree/master/Win10_UWPSample

My full error:

	System.Exception: NurApiConnectTransport() error 4098
	   at NurApiDotNet.UWP.NurApiTransport.<ConnectApi>d__35.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NurApiDotNet.NurApi.<ConnectAsync>d__1072.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at NurApiDotNet.NurApi.<ConnectAsync>d__1070.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at NordicBridge.ViewModels.MainViewModel.<<get_ConnectCommand>b__35_0>d.MoveNext()

Do you know what causes this error and can you give any advice? 

Many thanks!
Ste

**Comment by mikkonid** [comment]
Have you added needed device capabilities to Package.appxmanifest in <Capabilities> tag?

For BLE nur devices you'll need:
  ` <DeviceCapability Name="bluetooth" />`

And for serial (and USB nur) you'll need:
```
    <DeviceCapability Name="serialcommunication">
      <Device Id="any">
        <Function Type="name:serialPort" />
      </Device>
    </DeviceCapability>
```

**Comment by SteGriff** [comment]
Hi Mikko!

Thanks! Despite your message getting mangled by Markdown a little bit, you pointed me in the right direction; my app now works! For other readers, I copied the Capabilities section of `Package.appxmanifest` from NurApiSampleMvvm:

	<Capabilities>
		<Capability Name="internetClient" />
		<Capability Name="internetClientServer" />
		<Capability Name="privateNetworkClientServer" />
		<DeviceCapability Name="bluetooth" />
		<DeviceCapability Name="serialcommunication">
			<Device Id="any">
				<Function Type="name:serialPort" />
			</Device>
		</DeviceCapability>
	</Capabilities>

**Comment by mikkonid** [comment]
Hi Ste,
Good to hear you got it working!

Just added minimal sample:
https://github.com/NordicID/nur_sample_windows/tree/master/Win10_UWPSample/NurApiMinimalUWP

Also added note about capabilities to docs.
